# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'npm'
    directory: '/packages/xerox-browserslist-config'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'npm'
    directory: '/packages/xerox-commitlint-config'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'npm'
    directory: '/packages/xerox-eslint-config'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'npm'
    directory: '/packages/xerox-prettier-config'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'npm'
    directory: '/packages/xerox-semantic-release-config'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'npm'
    directory: '/packages/xerox-stylelint-config'
    schedule:
      interval: 'daily'
    target-branch: 'next'
    labels:
      - 'change: dependencies'
    allow:
      - dependency-type: 'direct'
