version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.14.1
  resource_class: small

jobs:
  install_lint_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{ checksum "./yarn.lock" }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - save_cache:
          key: node-10-cache-{{ checksum "./yarn.lock" }}
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - '4f:b2:be:1d:23:4f:8f:09:92:49:64:d8:ca:0e:10:2e'
      - run:
          name: Configure git
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git config --global user.email "xeroxinteractive-circleci@xerox.com"
            git config --global user.name "CircleCI"
      - run:
          name: Deploy package to npm
          command: yarn deploy

workflows:
  version: 2
  install_lint_test_deploy:
    jobs:
      - install_lint_test
      - deploy:
          requires:
            - install_lint_test
          filters:
            branches:
              only:
                - master
