version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts
  resource_class: small

jobs:
  install_lint_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{ checksum "./yarn.lock" }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - save_cache:
          key: node-10-cache-{{ checksum "./yarn.lock" }}
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - '94:aa:2d:64:14:93:c8:2f:cb:98:b5:4f:ec:96:80:86'
      - run:
          name: Configure git
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git config --global user.email "xeroxinteractive-circleci@xerox.com"
            git config --global user.name "CircleCI"
      - run:
          name: Deploy package to npm
          command: yarn deploy

  browserslist-stats:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{ checksum "./yarn.lock" }}
      - run: yarn install
      - run: yarn workspace @xerox/browserslist-config run update:stats

workflows:
  version: 2
  install_lint_test_deploy:
    jobs:
      - install_lint_test
      - deploy:
          requires:
            - install_lint_test
          filters:
            branches:
              only:
                - master
  browserslist-stats-cron:
    triggers:
      - schedule:
          cron: '0 15 2 * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - browserslist-stats
