version: 2

defaults: &defaults
  working_directory: ~/repo
  resource_class: small

install_lint_test: &install_lint_test
  steps:
    - checkout
    - restore_cache:
        keys:
          - node-{{ .Environment.NODE_VERSION }}-cache-{{ checksum "./yarn.lock" }}
    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - save_cache:
        key: node-{{ .Environment.NODE_VERSION }}-cache-{{ checksum "./yarn.lock" }}
        paths:
          - ~/.yarn-cache
          - ./node_modules
    - persist_to_workspace:
        root: ~/repo
        paths:
          - ./

jobs:
  install_lint_test-node10:
    docker:
      - image: circleci/node:10
    <<: [*defaults, *install_lint_test]

  install_lint_test-node12:
    docker:
      - image: circleci/node:12
    <<: [*defaults, *install_lint_test]

  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - '94:aa:2d:64:14:93:c8:2f:cb:98:b5:4f:ec:96:80:86'
      - run:
          name: Configure git
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git config --global user.email "xeroxinteractive-circleci@xerox.com"
            git config --global user.name "CircleCI"
      - run:
          name: Deploy package to npm
          command: yarn deploy

  browserslist-stats:
    <<: *defaults
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '94:aa:2d:64:14:93:c8:2f:cb:98:b5:4f:ec:96:80:86'
      - run:
          name: Configure git
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git config --global user.email "jenkinsbuilder@documentsmart.com"
            git config --global user.name "xeroxinteractive-builder"
      - run:
          name: Switch to dev branch
          command: |
            git fetch origin dev
            git checkout -b dev
      - restore_cache:
          keys:
            - node-10-cache-{{ checksum "./yarn.lock" }}
      - run: yarn install
      - run:
          name: Create new stats file
          command: |
            BAA_PRIVATE_KEY="$(echo $PRIVATE_KEY | base64 --decode)" yarn workspace @xerox/browserslist-config run update:stats
            npx prettier ./packages/xerox-browserslist-config/browserslist-stats.json --write
            git commit -a -m 'chore(browserslist-config): update stats'
      - run:
          name: Push branch
          command: |
            cd ~/repo
            git push --set-upstream origin dev
      - run:
          name: Create PR
          command: |
            cd ~
            wget https://github.com/github/hub/releases/download/v2.11.2/hub-linux-amd64-2.11.2.tgz
            tar xvfz hub-linux-amd64-2.11.2.tgz
            cd ~/repo
            ~/hub-linux-amd64-2.11.2/bin/hub pull-request --file .circleci/stats-cron-pr.md --base master

workflows:
  version: 2
  install_lint_test_deploy:
    jobs:
      - install_lint_test-node10:
          context: node10
      - install_lint_test-node12:
          context: node12
      - deploy:
          requires:
            - install_lint_test-node10
            - install_lint_test-node12
          filters:
            branches:
              only:
                - master
  browserslist-stats-cron:
    triggers:
      - schedule:
          cron: '30 14 10 * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - browserslist-stats
