# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    target_branch: 'next'
    default_labels:
      - 'dependencies'
    commit_message:
      prefix: 'chore'
      include_scope: true
    allowed_updates:
      - match:
          dependency_type: 'direct'
          update_type: 'all'
